/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  image_item: {
    width: '49%',
    marginTop: 12,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonUpload: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 200,
    backgroundColor: '#f2f2f2',
    borderRadius: 8,
  },
  frameContainer: {
    height: '100%',
    width: '100%',
    // backgroundColor: 'transparent',
    // borderTopColor: 'transparent',
    // borderLeftColor: 'transparent',
    // borderRightColor: 'transparent',
    // borderBottomColor: 'transparent',
    // borderTopWidth: 30,
    // borderLeftWidth: 40,
    // borderRightWidth: 40,
    // borderBottomWidth: 30,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  frameCamera: {
    // position: 'absolute',
    // top: '50%',
    // left: '50%',
    // transform: [{translateX: -80}, {translateY: -30}],
  },
  frame1: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 20,
    height: 20,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#0589FF',
    borderRightColor: '#0589FF',
  },
  frame2: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 20,
    height: 20,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopColor: '#0589FF',
    borderLeftColor: '#0589FF',
  },
  frame3: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 20,
    height: 20,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomColor: '#0589FF',
    borderLeftColor: '#0589FF',
  },
  frame4: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 20,
    height: 20,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderBottomColor: '#0589FF',
    borderRightColor: '#0589FF',
  },
  frame5: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.1)',
  },

  typeUpload: {
    fontWeight: 'bold',
    marginVertical: 10,
    marginBottom: 'auto',
    marginHorizontal: 10,
    // fontSize: 16,
  },
  image_title: {
    fontSize: 15,
    marginBottom: 12,
  },
  image: {
    width: '100%',
    height: '100%',
  },
  imageUploadIcons: {
    width: '100%',
    height: 60,
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{translateX: -90}, {translateY: -20}],
  },
  btn_upload: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    marginBottom: 12,
  },
  btn_text: {
    fontWeight: 'bold',
    fontSize: 12,
    textAlign: 'center',
  },
});

export default styles;
